### ISSUE TITLE
Language changes in de.locallang.xlf

### ISSUE THREAD

**Issue by Batman777** [hojaonline/pits_downloadcenter#7]
Editid the following file:
typo3conf/ext/pits_downloadcenter/Resources/Private/Language/
**de.locallang.xlf**

changed 

			<trans-unit id="tx_pitsdownloadcenter_domain_model_download.searchbytype">
				<source>Filter by file types</source>
				<target>Filtern nach **Dateitypen**</target>
			</trans-unit>

to

			<trans-unit id="tx_pitsdownloadcenter_domain_model_download.searchbytype">
				<source>Filter by file types</source>
				<target>Filtern nach **Dateiendungen**</target>
			</trans-unit>

Unfortunately I can't see any changes. Do you have a hint what went wrong?
Cheers
Eric

**Comment by Batman777** [comment]
"Dateitypen" should be replaced with "Dateiendungen"

**Comment by hojaonline** [comment]
@Batman777 : Sorry for the late response. It may be due to TYPO3 system cache it's not reflected. You could check by clearing install tool cache. 

NP. Better you should override the language translations through typoscript instead of directly changing it in extension folder.
[
plugin.tx_my_extension_pi1._LOCAL_LANG.de.marker = neuer Text  
plugin.tx_my_extension_pi1._LOCAL_LANG.en.marker = new text  
]

**Comment by Batman777** [comment]
Thank you :-) - The following TS did the trick.

plugin.tx_pitsdownloadcenter._LOCAL_LANG.de.tx_pitsdownloadcenter_domain_model_download.searchbytype = New Text here
